### ISSUE TITLE
StatusCodeError: 403 - "{\"message\":\"login_required\",\"status\":\"fail\"}"

### ISSUE THREAD

**Issue by n1kko777** [amamenko/daily-pixel-mike#1]
Hello! Do you know why I can get 403 error, when I try to upload a photo? But before publish i got a message "Login successful!"

https://github.com/amamenko/daily-pixel-mike/blob/799753f6d4a0fc0e1acfcfc2e8e0e6dd72279615/index.ts#L112

**Comment by amamenko** [comment]
Here, keep in mind that the Instagram post function takes the current client as an **argument** (this will be the client used after successfully logging in):
```
await client
      .login()
      .then(() => {
            console.log("Login successful!");
            instagramPostFunction(client);
      })
```
This argument is then defined as such within the function:
```
const instagramPostFunction = (currentClient: typeof client) => {
```
and ultimately used to call the `uploadPhoto` method:
```
await currentClient
      .uploadPhoto({
            photo: "./your_photo.jpg",
            caption,
            post: "feed",
      })
```

**Comment by n1kko777** [comment]
Yeah, it's correct. I think it's depends on insta user and pass. I launch your app with my credentials and it return the same result (403). I've got multi-account where 2 profile with one email probably it's a reason of 403 error.

**Comment by n1kko777** [comment]
Yes, I was right. When I created a completely new account, everything worked successfully, thanks for the cool project!
